# fly.toml file generated for amirightladies-python on 2022-03-25T02:07:25-06:00

app = "amirightladies-python"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

[deploy]
  release_command = "aerich upgrade"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = ["python3", "main.py"]
