-- upgrade --
CREATE TABLE IF NOT EXISTS "guild" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "exid" INT NOT NULL
);
CREATE TABLE IF NOT EXISTS "member" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "exid" INT NOT NULL,
    "name" VARCHAR(64) NOT NULL,
    "nick" VARCHAR(64),
    "discriminator" VARCHAR(64) NOT NULL,
    "bot" INT NOT NULL  DEFAULT 0
);
CREATE TABLE IF NOT EXISTS "song" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "stream_id" VARCHAR(512) NOT NULL UNIQUE,
    "title" VARCHAR(512) NOT NULL,
    "url" VARCHAR(512) NOT NULL,
    "file" VARCHAR(512) NOT NULL
);
CREATE TABLE IF NOT EXISTS "defersong" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "query" VARCHAR(128) NOT NULL  DEFAULT '',
    "created_at" TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "guild_id" INT REFERENCES "guild" ("id") ON DELETE CASCADE,
    "song_id" INT REFERENCES "song" ("id") ON DELETE CASCADE,
    "next_id" INT  UNIQUE REFERENCES "defersong" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "historysong" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "created_at" TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "guild_id" INT NOT NULL REFERENCES "guild" ("id") ON DELETE CASCADE,
    "song_id" INT NOT NULL REFERENCES "song" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "aerich" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(20) NOT NULL,
    "content" JSON NOT NULL
);
CREATE TABLE IF NOT EXISTS "member_guild" (
    "member_id" INT NOT NULL REFERENCES "member" ("id") ON DELETE CASCADE,
    "guild_id" INT NOT NULL REFERENCES "guild" ("id") ON DELETE CASCADE
);
